package Laporan;
import koneksi.koneksi;
import java.io.InputStream;
import java.sql.Connection;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import com.toedter.calendar.JDateChooser; 
import MenuUtama.MenuUtama;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FormLaporanPenjualan extends javax.swing.JFrame {
     private MenuUtama menuUtamaAsal;

    public FormLaporanPenjualan() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Parameter Laporan Pembelian");
        jdcTanggalAwalLap.setDate(new Date());
        jdcTanggalAkhirLap.setDate(new Date());
    }

    public FormLaporanPenjualan(MenuUtama pemanggilMenu) {
        initComponents();
        this.menuUtamaAsal = pemanggilMenu;
        setLocationRelativeTo(pemanggilMenu);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Parameter Laporan Penjualan");
        jdcTanggalAwalLap.setDate(new Date());
        jdcTanggalAkhirLap.setDate(new Date());
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jdcTanggalAwalLap = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jdcTanggalAkhirLap = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnProsesTampilkanLapPenjualan = new javax.swing.JButton();
        btnBatalInputLap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Periode Laporan Penjualan");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 440, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tanggal Awal");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));
        jPanel3.add(jdcTanggalAwalLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 160, -1));

        jLabel3.setText("Tanggal Akhir");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));
        jPanel3.add(jdcTanggalAkhirLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProsesTampilkanLapPenjualan.setText("Tampilkan Laporan");
        btnProsesTampilkanLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesTampilkanLapPenjualanActionPerformed(evt);
            }
        });
        jPanel4.add(btnProsesTampilkanLapPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnBatalInputLap.setText("Batal");
        btnBatalInputLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalInputLapActionPerformed(evt);
            }
        });
        jPanel4.add(btnBatalInputLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 430, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesTampilkanLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesTampilkanLapPenjualanActionPerformed
        try {
            Date tanggalAwal = jdcTanggalAwalLap.getDate();
            Date tanggalAkhir = jdcTanggalAkhirLap.getDate();
            if (tanggalAwal == null || tanggalAkhir == null) {
                JOptionPane.showMessageDialog(this, "Tanggal awal dan tanggal akhir harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (tanggalAwal.after(tanggalAkhir)) {
                JOptionPane.showMessageDialog(this, "Tanggal awal tidak boleh setelah tanggal akhir!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Connection conn = new koneksi().connect();
            String pathJasper = "/Laporan/LaporanPenjualan.jasper";
            InputStream jasperStream = getClass().getResourceAsStream(pathJasper);
            if (jasperStream == null) {
                JOptionPane.showMessageDialog(this, "File LaporanPenjualan.jasper tidak ditemukan di: " + pathJasper, "Error File", JOptionPane.ERROR_MESSAGE);
                return;
            }
            HashMap<String, Object> parameter = new HashMap<>();
            parameter.put("TGL_AWAL", tanggalAwal);
            parameter.put("TGL_AKHIR", tanggalAkhir);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperStream, parameter, conn);
            if (jasperPrint.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada data penjualan untuk periode tanggal yang dipilih.", "Informasi Laporan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JasperViewer.viewReport(jasperPrint, false); 
            }
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan laporan penjualan: " + e.getMessage(), "Error Laporan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan umum: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnProsesTampilkanLapPenjualanActionPerformed

    private void btnBatalInputLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalInputLapActionPerformed
        this.dispose();
        if (menuUtamaAsal != null) {
        menuUtamaAsal.tampilkanPanel("Laporan");
        menuUtamaAsal.setVisible(true);
    } else {
        new MenuUtama().setVisible(true);
    }
    }//GEN-LAST:event_btnBatalInputLapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporanPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalInputLap;
    private javax.swing.JButton btnProsesTampilkanLapPenjualan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jdcTanggalAkhirLap;
    private com.toedter.calendar.JDateChooser jdcTanggalAwalLap;
    // End of variables declaration//GEN-END:variables
}
