package Laporan;
import koneksi.koneksi;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import MenuUtama.MenuUtama;

public class FormLaporanStok extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private MenuUtama menuUtamaAsal;
    
    public FormLaporanStok() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Parameter Laporan Stok");
        loadKategori();
        txtBatasStokKritis.setEnabled(false);
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolean isSelected = j1.isSelected();
                txtBatasStokKritis.setEnabled(isSelected);
                if (!isSelected) {
                    txtBatasStokKritis.setText("");
                }
            }
        });
    }
    
    public FormLaporanStok(MenuUtama pemanggilMenu) {
        initComponents();
        this.menuUtamaAsal = pemanggilMenu;
        setLocationRelativeTo(pemanggilMenu);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Parameter Laporan Stok");
        loadKategori();
        txtBatasStokKritis.setEnabled(false);
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolean isSelected = j1.isSelected();
                txtBatasStokKritis.setEnabled(isSelected);
                if (!isSelected) {
                    txtBatasStokKritis.setText("");
                }
            }
        });
    }

        private void loadKategori() {
            cmbKategoriLapStok.removeAllItems();
            cmbKategoriLapStok.addItem("-- Semua Kategori --"); 
    try {
        String sql = "SELECT id_kategori, nama_kategori FROM kategori_mainan ORDER BY id_kategori ASC";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            cmbKategoriLapStok.addItem(hasil.getString("id_kategori") + " - " + hasil.getString("nama_kategori"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data kategori: " + e);
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnTampilkanLapStok = new javax.swing.JButton();
        btnBatalInputLapStok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbKategoriLapStok = new javax.swing.JComboBox<>();
        j1 = new javax.swing.JCheckBox();
        jLabelBatasStok = new javax.swing.JLabel();
        txtBatasStokKritis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan Stok Mainan");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 440, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTampilkanLapStok.setText("Tampilkan Laporan");
        btnTampilkanLapStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanLapStokActionPerformed(evt);
            }
        });
        jPanel4.add(btnTampilkanLapStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnBatalInputLapStok.setText("Batal");
        btnBatalInputLapStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalInputLapStokActionPerformed(evt);
            }
        });
        jPanel4.add(btnBatalInputLapStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 430, 70));

        jLabel2.setText("Pilih Kategori");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        cmbKategoriLapStok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cmbKategoriLapStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, -1));

        j1.setText("Filter Stok Kritis (Stok <= Batas)");
        jPanel3.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 90, 250, -1));

        jLabelBatasStok.setText("Batas Stok Kritis");
        jPanel3.add(jLabelBatasStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));
        jPanel3.add(txtBatasStokKritis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanLapStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanLapStokActionPerformed
        try {
            Connection reportConn = new koneksi().connect();
            String pathJasper = "/laporan/LaporanStokMainan.jasper";
            InputStream jasperStream = getClass().getResourceAsStream(pathJasper);
            if (jasperStream == null) {
                JOptionPane.showMessageDialog(this, "File LaporanStokMainan.jasper tidak ditemukan di: " + pathJasper, "Error File", JOptionPane.ERROR_MESSAGE);
                return;
            }
            HashMap<String, Object> parameter = new HashMap<>();
            String idKategoriDipilih = null;
            if (cmbKategoriLapStok.getSelectedIndex() > 0) {
                String itemTerpilih = cmbKategoriLapStok.getSelectedItem().toString();
                idKategoriDipilih = itemTerpilih.split(" - ")[0];
            }
            parameter.put("P_ID_KATEGORI", idKategoriDipilih == null ? "" : idKategoriDipilih);
            Integer batasStokKritis = null;
            if (j1.isSelected()) {
                try {
                    batasStokKritis = Integer.parseInt(txtBatasStokKritis.getText());
                    if (batasStokKritis < 0) {
                        JOptionPane.showMessageDialog(this, "Batas stok kritis tidak boleh negatif.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                        txtBatasStokKritis.requestFocus();
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Batas stok kritis harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    txtBatasStokKritis.requestFocus();
                    return;
                }
            }
            parameter.put("P_BATAS_STOK_KRITIS", batasStokKritis == null ? -1 : batasStokKritis);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperStream, parameter, reportConn);
            if (jasperPrint.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada data stok yang sesuai dengan filter yang dipilih.", "Informasi Laporan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JasperViewer.viewReport(jasperPrint, false);
            }
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan laporan stok: " + e.getMessage(), "Error Laporan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan umum: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTampilkanLapStokActionPerformed

    private void btnBatalInputLapStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalInputLapStokActionPerformed
        this.dispose();
        if (menuUtamaAsal != null) {
            menuUtamaAsal.tampilkanPanel("Laporan");
            menuUtamaAsal.setVisible(true);
        } else {
             new MenuUtama().setVisible(true);
        }
    }//GEN-LAST:event_btnBatalInputLapStokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporanStok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalInputLapStok;
    private javax.swing.JButton btnTampilkanLapStok;
    private javax.swing.JComboBox<String> cmbKategoriLapStok;
    private javax.swing.JCheckBox j1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBatasStok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtBatasStokKritis;
    // End of variables declaration//GEN-END:variables
}
