package Laporan;
import koneksi.koneksi;
import java.io.InputStream;
import java.sql.Connection;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import com.toedter.calendar.JDateChooser;
import MenuUtama.MenuUtama;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FormLaporanPembelian extends javax.swing.JFrame {
    private MenuUtama menuUtamaAsal;

    public FormLaporanPembelian() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Parameter Laporan Pembelian");
        jdcTanggalAwalLapBeli.setDate(new Date());
        jdcTanggalAkhirLapBeli.setDate(new Date());
    }

    public FormLaporanPembelian(MenuUtama pemanggilMenu) {
        initComponents();
        this.menuUtamaAsal = pemanggilMenu;
        setLocationRelativeTo(pemanggilMenu);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Parameter Laporan Pembelian");
        jdcTanggalAwalLapBeli.setDate(new Date());
        jdcTanggalAkhirLapBeli.setDate(new Date());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jdcTanggalAwalLapBeli = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jdcTanggalAkhirLapBeli = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnProsesTampilkanLapPembelian = new javax.swing.JButton();
        btnBatalInputLapBeli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Periode Laporan Pembelian");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 440, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tanggal Awal");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));
        jPanel3.add(jdcTanggalAwalLapBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 160, -1));

        jLabel3.setText("Tanggal Akhir");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));
        jPanel3.add(jdcTanggalAkhirLapBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProsesTampilkanLapPembelian.setText("Tampilkan Laporan");
        btnProsesTampilkanLapPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesTampilkanLapPembelianActionPerformed(evt);
            }
        });
        jPanel4.add(btnProsesTampilkanLapPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnBatalInputLapBeli.setText("Batal");
        btnBatalInputLapBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalInputLapBeliActionPerformed(evt);
            }
        });
        jPanel4.add(btnBatalInputLapBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 430, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 430, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesTampilkanLapPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesTampilkanLapPembelianActionPerformed
    try {
            Date tanggalAwal = jdcTanggalAwalLapBeli.getDate();
            Date tanggalAkhir = jdcTanggalAkhirLapBeli.getDate();
            if (tanggalAwal == null || tanggalAkhir == null) {
                JOptionPane.showMessageDialog(this, "Tanggal awal dan tanggal akhir harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (tanggalAwal.after(tanggalAkhir)) {
                JOptionPane.showMessageDialog(this, "Tanggal awal tidak boleh setelah tanggal akhir!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Connection conn = new koneksi().connect();
            String pathJasper = "/Laporan/LaporanPembelian.jasper";
            InputStream jasperStream = getClass().getResourceAsStream(pathJasper);
            if (jasperStream == null) {
                JOptionPane.showMessageDialog(this, 
                    "File laporan LaporanPembelian.jasper tidak ditemukan di path: " + pathJasper +
                    "\nPastikan file sudah ada di folder src/laporan/ dan proyek sudah di-Clean and Build.", 
                    "Error File Laporan", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            HashMap<String, Object> parameter = new HashMap<>();
            parameter.put("TGL_AWAL_PEMBELIAN", tanggalAwal); 
            parameter.put("TGL_AKHIR_PEMBELIAN", tanggalAkhir);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperStream, parameter, conn);
            if (jasperPrint.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada data pembelian untuk periode tanggal yang dipilih.", "Informasi Laporan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JasperViewer.viewReport(jasperPrint, false); 
            }
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan laporan pembelian: " + e.getMessage(), "Error Laporan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan umum: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnProsesTampilkanLapPembelianActionPerformed

    private void btnBatalInputLapBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalInputLapBeliActionPerformed
        this.dispose();
        if (menuUtamaAsal != null) {
            menuUtamaAsal.tampilkanPanel("Laporan");
            menuUtamaAsal.setVisible(true);
        } else {
             new MenuUtama().setVisible(true);
        }
    }//GEN-LAST:event_btnBatalInputLapBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporanPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalInputLapBeli;
    private javax.swing.JButton btnProsesTampilkanLapPembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JDateChooser jdcTanggalAkhirLapBeli;
    private com.toedter.calendar.JDateChooser jdcTanggalAwalLapBeli;
    // End of variables declaration//GEN-END:variables
}
