package Transaksi;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import Transaksi.PembelianMainan;

public class PopUpCariMainan extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public PembelianMainan frmPembelian = null;
    private DecimalFormat df = new DecimalFormat("###0");
    private String idSupplierFilter; 
    
    public PopUpCariMainan() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
     
    public void initData(String idSupplier, PembelianMainan framePembelian) {
        this.idSupplierFilter = idSupplier;
        this.frmPembelian = framePembelian;
        setLocationRelativeTo(null);
        datatable();
    }
   
     protected void datatable() {
        Object[] Baris = {"ID Mainan", "Nama Mainan", "Harga Beli", "Stok"};
        tabmode = new DefaultTableModel(null, Baris);
        if (tblMainanPopUp == null) { 
            System.err.println("tblMainanPopUp belum diinisialisasi!");
            return;
        }
        tblMainanPopUp.setModel(tabmode);
        String cariitem = (txtCariPopUp != null) ? txtCariPopUp.getText() : "";
        if (this.idSupplierFilter == null || this.idSupplierFilter.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier belum dipilih untuk filter mainan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            return; 
        }
        try {
            String sql = "SELECT id_mainan, nama_mainan, harga_beli, stok FROM mainan "
                       + "WHERE id_supplier = ? AND (id_mainan LIKE ? OR nama_mainan LIKE ?) "
                       + "ORDER BY id_mainan ASC";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, this.idSupplierFilter);
            stat.setString(2, "%" + cariitem + "%");
            stat.setString(3, "%" + cariitem + "%");
            ResultSet hasil = stat.executeQuery();
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_mainan"),
                    hasil.getString("nama_mainan"),
                    df.format(hasil.getDouble("harga_beli")),
                    hasil.getInt("stok")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data mainan gagal ditampilkan: " + e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariPopUp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMainanPopUp = new javax.swing.JTable();
        btnPilihMainan = new javax.swing.JButton();
        btnBatalPopUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cari Data Mainan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("Cari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtCariPopUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPopUpKeyReleased(evt);
            }
        });
        jPanel1.add(txtCariPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 130, -1));

        tblMainanPopUp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMainanPopUp.setGridColor(new java.awt.Color(0, 0, 0));
        tblMainanPopUp.setShowGrid(true);
        jScrollPane1.setViewportView(tblMainanPopUp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 110));

        btnPilihMainan.setText("Pilih");
        btnPilihMainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMainanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihMainan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, -1));

        btnBatalPopUp.setText("Batal");
        btnBatalPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariPopUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPopUpKeyReleased
         datatable();
    }//GEN-LAST:event_txtCariPopUpKeyReleased

    private void btnPilihMainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMainanActionPerformed
         int barisTerpilih = tblMainanPopUp.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih mainan terlebih dahulu.");
            return;
        }
        if (frmPembelian != null) {
            frmPembelian.idMainanTerpilih = tblMainanPopUp.getValueAt(barisTerpilih, 0).toString();
            frmPembelian.namaMainanTerpilih = tblMainanPopUp.getValueAt(barisTerpilih, 1).toString();
            try {
                String sqlHarga = "SELECT harga_beli FROM mainan WHERE id_mainan = ?";
                PreparedStatement statHarga = conn.prepareStatement(sqlHarga);
                statHarga.setString(1, frmPembelian.idMainanTerpilih);
                ResultSet rsHarga = statHarga.executeQuery();
                if (rsHarga.next()) {
                    frmPembelian.hargaBeliTerpilih = rsHarga.getDouble("harga_beli");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal mengambil harga beli: " + e);
                frmPembelian.hargaBeliTerpilih = 0; 
            }
            frmPembelian.mainanTerpilih();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Referensi ke Form Pembelian tidak valid!");
        }
    }//GEN-LAST:event_btnPilihMainanActionPerformed

    private void btnBatalPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPopUpActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalPopUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpCariMainan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPopUp;
    private javax.swing.JButton btnPilihMainan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMainanPopUp;
    private javax.swing.JTextField txtCariPopUp;
    // End of variables declaration//GEN-END:variables
}
