package Transaksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

public class PopUpPilihMainanStok extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public PengelolaanStok frmPengelolaanStok = null; 

    public PopUpPilihMainanStok() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public void initData(PengelolaanStok framePengelolaStok) {
        this.frmPengelolaanStok = framePengelolaStok;
        setLocationRelativeTo(framePengelolaStok);
        datatable();
    }
    
    protected void datatable() {
        Object[] Baris = {"ID Mainan", "Nama Mainan", "Stok Saat Ini"};
        tabmode = new DefaultTableModel(null, Baris);
        tblMainanStokPopUp.setModel(tabmode); 
        String cariitem = txtCariMainanStokPopUp.getText();
        try {
            String sql = "SELECT id_mainan, nama_mainan, stok FROM mainan "
                       + "WHERE id_mainan LIKE ? OR nama_mainan LIKE ? "
                       + "ORDER BY id_mainan ASC";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, "%" + cariitem + "%");
            stat.setString(2, "%" + cariitem + "%");
            ResultSet hasil = stat.executeQuery();
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_mainan"),
                    hasil.getString("nama_mainan"),
                    hasil.getInt("stok") 
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data mainan gagal ditampilkan untuk PopUp Stok: " + e);
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariMainanStokPopUp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMainanStokPopUp = new javax.swing.JTable();
        btnPilihMainanStokPopUp = new javax.swing.JButton();
        btnBatalStokPopUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pilih Mainan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("Cari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtCariMainanStokPopUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMainanStokPopUpKeyReleased(evt);
            }
        });
        jPanel1.add(txtCariMainanStokPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 130, -1));

        tblMainanStokPopUp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMainanStokPopUp.setGridColor(new java.awt.Color(0, 0, 0));
        tblMainanStokPopUp.setShowGrid(true);
        jScrollPane1.setViewportView(tblMainanStokPopUp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 110));

        btnPilihMainanStokPopUp.setText("Pilih");
        btnPilihMainanStokPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMainanStokPopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihMainanStokPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, -1));

        btnBatalStokPopUp.setText("Batal");
        btnBatalStokPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalStokPopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalStokPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariMainanStokPopUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMainanStokPopUpKeyReleased
        datatable();
    }//GEN-LAST:event_txtCariMainanStokPopUpKeyReleased

    private void btnPilihMainanStokPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMainanStokPopUpActionPerformed
    int barisTerpilih = tblMainanStokPopUp.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih mainan terlebih dahulu dari tabel.");
            return;
        }
        if (frmPengelolaanStok != null) {
            frmPengelolaanStok.idMainanTerpilihStok = tblMainanStokPopUp.getValueAt(barisTerpilih, 0).toString();
            frmPengelolaanStok.namaMainanTerpilihStok = tblMainanStokPopUp.getValueAt(barisTerpilih, 1).toString();
            frmPengelolaanStok.stokAwalMainanTerpilih = Integer.parseInt(tblMainanStokPopUp.getValueAt(barisTerpilih, 2).toString());
            frmPengelolaanStok.mainanUntukPenyesuaianTerpilih(); 
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Referensi ke Form Pengelolaan Stok tidak valid atau belum di-set!");
        }
    }//GEN-LAST:event_btnPilihMainanStokPopUpActionPerformed

    private void btnBatalStokPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalStokPopUpActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalStokPopUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihMainanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihMainanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihMainanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpPilihMainanStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpPilihMainanStok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalStokPopUp;
    private javax.swing.JButton btnPilihMainanStokPopUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMainanStokPopUp;
    private javax.swing.JTextField txtCariMainanStokPopUp;
    // End of variables declaration//GEN-END:variables
}
