package Transaksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import Transaksi.PembelianMainan;

public class PopUpCariSupplier extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public PembelianMainan frmPembelian = null;
    public PopUpCariSupplier() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
    }

     protected void datatable() {
        Object[] Baris = {"ID Supplier", "Nama Supplier", "Alamat", "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        tblSupplierPopUp.setModel(tabmode);
        String cariitem = txtCariSupplierPopUp.getText();
        try {
            String sql = "SELECT * FROM supplier WHERE id_supplier LIKE ? OR nama_supplier LIKE ? ORDER BY id_supplier ASC";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, "%" + cariitem + "%");
            stat.setString(2, "%" + cariitem + "%");
            ResultSet hasil = stat.executeQuery();
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_supplier"),
                    hasil.getString("nama_supplier"),
                    hasil.getString("alamat"),
                    hasil.getString("no_telp")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data supplier gagal ditampilkan: " + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariSupplierPopUp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierPopUp = new javax.swing.JTable();
        btnPilihSupplier = new javax.swing.JButton();
        btnBatalSupplierPopUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cari Data Supplier");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("Cari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtCariSupplierPopUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariSupplierPopUpKeyReleased(evt);
            }
        });
        jPanel1.add(txtCariSupplierPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 130, -1));

        tblSupplierPopUp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplierPopUp.setGridColor(new java.awt.Color(0, 0, 0));
        tblSupplierPopUp.setShowGrid(true);
        jScrollPane1.setViewportView(tblSupplierPopUp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 110));

        btnPilihSupplier.setText("Pilih");
        btnPilihSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, -1));

        btnBatalSupplierPopUp.setText("Batal");
        btnBatalSupplierPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalSupplierPopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalSupplierPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariSupplierPopUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariSupplierPopUpKeyReleased
        datatable();
    }//GEN-LAST:event_txtCariSupplierPopUpKeyReleased

    private void btnPilihSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihSupplierActionPerformed
        int barisTerpilih = tblSupplierPopUp.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih supplier terlebih dahulu.");
            return;
        }
        frmPembelian.idSupplierTerpilih = tblSupplierPopUp.getValueAt(barisTerpilih, 0).toString();
        frmPembelian.namaSupplierTerpilih = tblSupplierPopUp.getValueAt(barisTerpilih, 1).toString();
        frmPembelian.supplierTerpilih();
        this.dispose();
    }//GEN-LAST:event_btnPilihSupplierActionPerformed

    private void btnBatalSupplierPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalSupplierPopUpActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalSupplierPopUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpCariSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpCariSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpCariSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpCariSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpCariSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalSupplierPopUp;
    private javax.swing.JButton btnPilihSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierPopUp;
    private javax.swing.JTextField txtCariSupplierPopUp;
    // End of variables declaration//GEN-END:variables
}
