package Transaksi;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

public class PopUpCariMainanJual extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public PenjualanMainan frmPenjualan = null; 
    private DecimalFormat df = new DecimalFormat("###0");

    public PopUpCariMainanJual() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public void initData(PenjualanMainan framePenjualan) {
        this.frmPenjualan = framePenjualan;
        setLocationRelativeTo(framePenjualan);
        datatable();
    }
    
    protected void datatable() {
        Object[] Baris = {"ID Mainan", "Nama Mainan", "Harga Jual", "Stok"};
        tabmode = new DefaultTableModel(null, Baris);
        tblMainanJualPopUp.setModel(tabmode);
        String cariitem = txtCariMainanJualPopUp.getText();
        try {
            String sql = "SELECT id_mainan, nama_mainan, harga_jual, stok FROM mainan "
                       + "WHERE (id_mainan LIKE ? OR nama_mainan LIKE ?) AND stok > 0 " // Hanya tampilkan mainan yang ada stok
                       + "ORDER BY id_mainan ASC";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, "%" + cariitem + "%");
            stat.setString(2, "%" + cariitem + "%");   
            ResultSet hasil = stat.executeQuery();
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_mainan"),
                    hasil.getString("nama_mainan"),
                    df.format(hasil.getDouble("harga_jual")),
                    hasil.getInt("stok")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data mainan gagal ditampilkan: " + e);
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCariMainanJualPopUp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMainanJualPopUp = new javax.swing.JTable();
        btnPilihMainanJualPopUp = new javax.swing.JButton();
        btnBatalMainanJualPopUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mainan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("Cari Mainan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtCariMainanJualPopUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMainanJualPopUpKeyReleased(evt);
            }
        });
        jPanel1.add(txtCariMainanJualPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        tblMainanJualPopUp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMainanJualPopUp.setGridColor(new java.awt.Color(0, 0, 0));
        tblMainanJualPopUp.setShowGrid(true);
        jScrollPane1.setViewportView(tblMainanJualPopUp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 110));

        btnPilihMainanJualPopUp.setText("Pilih");
        btnPilihMainanJualPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMainanJualPopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnPilihMainanJualPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, -1));

        btnBatalMainanJualPopUp.setText("Batal");
        btnBatalMainanJualPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalMainanJualPopUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalMainanJualPopUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariMainanJualPopUpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMainanJualPopUpKeyReleased
     datatable();
    }//GEN-LAST:event_txtCariMainanJualPopUpKeyReleased

    private void btnPilihMainanJualPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMainanJualPopUpActionPerformed
     int barisTerpilih = tblMainanJualPopUp.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih mainan terlebih dahulu.");
            return;
        }      
        if (frmPenjualan != null) {
            frmPenjualan.idMainanJualTerpilih = tblMainanJualPopUp.getValueAt(barisTerpilih, 0).toString();
            frmPenjualan.namaMainanJualTerpilih = tblMainanJualPopUp.getValueAt(barisTerpilih, 1).toString();
            try {
                String sqlDataAsli = "SELECT harga_jual, stok FROM mainan WHERE id_mainan = ?";
                PreparedStatement statDataAsli = conn.prepareStatement(sqlDataAsli);
                statDataAsli.setString(1, frmPenjualan.idMainanJualTerpilih);
                ResultSet rsDataAsli = statDataAsli.executeQuery();
                if (rsDataAsli.next()) {
                    frmPenjualan.hargaJualTerpilih = rsDataAsli.getDouble("harga_jual");
                    frmPenjualan.stokSaatIniTerpilih = rsDataAsli.getInt("stok");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal mengambil detail data mainan: " + e);
                frmPenjualan.hargaJualTerpilih = 0;
                frmPenjualan.stokSaatIniTerpilih = 0;
            }    
            frmPenjualan.mainanJualTerpilih();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Referensi ke Form Penjualan tidak valid!");
        }
    }//GEN-LAST:event_btnPilihMainanJualPopUpActionPerformed

    private void btnBatalMainanJualPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalMainanJualPopUpActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalMainanJualPopUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainanJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainanJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainanJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpCariMainanJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpCariMainanJual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalMainanJualPopUp;
    private javax.swing.JButton btnPilihMainanJualPopUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMainanJualPopUp;
    private javax.swing.JTextField txtCariMainanJualPopUp;
    // End of variables declaration//GEN-END:variables
}
