package MenuUtama;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MenuUtama extends javax.swing.JFrame {
    private PanelHome panelHome;
    private PanelMasterPilihan panelMasterPilihan;
    private PanelTransaksiPilihan panelTransaksiPilihan;
    private PanelLaporanPilihan panelLaporanPilihan;
    
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
    setTitle("Menu Utama - Aplikasi Toko Mainan");
    panelHome = new PanelHome(); 
    panelMasterPilihan = new PanelMasterPilihan(this); 
    panelTransaksiPilihan = new PanelTransaksiPilihan(this);
    panelLaporanPilihan = new PanelLaporanPilihan(this);   

    int kontenWidth = 960; 
    int kontenHeight = 570; 

    panelHome.setBounds(0, 0, kontenWidth, kontenHeight);
    panelMasterPilihan.setBounds(0, 0, kontenWidth, kontenHeight);
    panelTransaksiPilihan.setBounds(0, 0, kontenWidth, kontenHeight);
    panelLaporanPilihan.setBounds(0, 0, kontenWidth, kontenHeight);
    panelKontenUtama.removeAll(); 

    
    panelKontenUtama.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, kontenWidth, kontenHeight));
    panelKontenUtama.add(panelMasterPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, kontenWidth, kontenHeight));
    panelKontenUtama.add(panelTransaksiPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, kontenWidth, kontenHeight));
    panelKontenUtama.add(panelLaporanPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, kontenWidth, kontenHeight));
    panelKontenUtama.revalidate();
    panelKontenUtama.repaint();


    panelHome.setVisible(true);
    panelMasterPilihan.setVisible(false);
    panelTransaksiPilihan.setVisible(false);
    panelLaporanPilihan.setVisible(false);

    tampilkanPanel("Home");
    }

    public void tampilkanPanel(String namaIdentifierPanel) {
        panelHome.setVisible(false);
        panelMasterPilihan.setVisible(false);
        panelTransaksiPilihan.setVisible(false);
        panelLaporanPilihan.setVisible(false);
        if ("Home".equalsIgnoreCase(namaIdentifierPanel)) {
            panelHome.setVisible(true);
            lblJudul.setText("HOME");
        } else if ("Master".equalsIgnoreCase(namaIdentifierPanel)) {
            panelMasterPilihan.setVisible(true);
            lblJudul.setText("MASTER");
        } else if ("Transaksi".equalsIgnoreCase(namaIdentifierPanel)) {
            panelTransaksiPilihan.setVisible(true);
            lblJudul.setText("TRANSAKSI");
        } else if ("Laporan".equalsIgnoreCase(namaIdentifierPanel)) {
            panelLaporanPilihan.setVisible(true);
            lblJudul.setText("LAPORAN");
        }
        panelKontenUtama.revalidate();
        panelKontenUtama.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnMaster = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        panelKontenUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 111, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("HOME");
        jPanel2.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 0, 170, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_master.png"))); // NOI18N
        btnMaster.setBorderPainted(false);
        btnMaster.setContentAreaFilled(false);
        btnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterActionPerformed(evt);
            }
        });
        jPanel3.add(btnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_home.png"))); // NOI18N
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel3.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_transaksi.png"))); // NOI18N
        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel3.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, -1));

        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_laporan.png"))); // NOI18N
        btnLaporan.setBorderPainted(false);
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jPanel3.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, -1));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button_keluar.png"))); // NOI18N
        btnKeluar.setBorderPainted(false);
        btnKeluar.setContentAreaFilled(false);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel3.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 570));

        panelKontenUtama.setBackground(new java.awt.Color(0, 77, 100));
        panelKontenUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelKontenUtama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jPanel1.add(panelKontenUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 960, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
   tampilkanPanel("Home");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        tampilkanPanel("Transaksi");
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        tampilkanPanel("Laporan");
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterActionPerformed
         tampilkanPanel("Master");
    }//GEN-LAST:event_btnMasterActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int Pilihan = JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin keluar?","Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
        if(Pilihan == JOptionPane.OK_OPTION){
            this.dispose();
            new Login.FormLogin().setVisible(true);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMaster;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelKontenUtama;
    // End of variables declaration//GEN-END:variables
}
