package MenuUtama;

import Master.*;
import Transaksi.*;
import Laporan.*;
import koneksi.koneksi;
import javax.swing.JOptionPane;

public class PanelMasterPilihan extends javax.swing.JPanel {
    private MenuUtama frameMenuUtama;
   
    public PanelMasterPilihan(MenuUtama frameUtamaDariPemanggil) {
        initComponents();
        this.frameMenuUtama = frameUtamaDariPemanggil;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKontenUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBukaFormDataMainan = new javax.swing.JButton();
        btnBukaFormDataKategori = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBukaFormDataSupplier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBukaFormDataPelanggan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        panelKontenUtama.setBackground(new java.awt.Color(0, 77, 100));
        panelKontenUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA MAINAN");
        panelKontenUtama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 230, 40));

        btnBukaFormDataMainan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Mainan.png"))); // NOI18N
        btnBukaFormDataMainan.setBorderPainted(false);
        btnBukaFormDataMainan.setContentAreaFilled(false);
        btnBukaFormDataMainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaFormDataMainanActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnBukaFormDataMainan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 200));

        btnBukaFormDataKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Kategori Mainan.png"))); // NOI18N
        btnBukaFormDataKategori.setBorderPainted(false);
        btnBukaFormDataKategori.setContentAreaFilled(false);
        btnBukaFormDataKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaFormDataKategoriActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnBukaFormDataKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 200, 200));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KATEGORI MAINAN");
        panelKontenUtama.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 230, 230, -1));

        btnBukaFormDataSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Supplier.png"))); // NOI18N
        btnBukaFormDataSupplier.setBorderPainted(false);
        btnBukaFormDataSupplier.setContentAreaFilled(false);
        btnBukaFormDataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaFormDataSupplierActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnBukaFormDataSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 200, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUPPLIER");
        panelKontenUtama.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 190, -1));

        btnBukaFormDataPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pelanggan.png"))); // NOI18N
        btnBukaFormDataPelanggan.setBorderPainted(false);
        btnBukaFormDataPelanggan.setContentAreaFilled(false);
        btnBukaFormDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaFormDataPelangganActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnBukaFormDataPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, 200));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PELANGGAN");
        panelKontenUtama.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 510, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelKontenUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelKontenUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBukaFormDataKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaFormDataKategoriActionPerformed
    if (this.frameMenuUtama != null) {
        Master.FormKategoriMainan frmKategori = new Master.FormKategoriMainan(this.frameMenuUtama); 
        frmKategori.setVisible(true);
        this.frameMenuUtama.setVisible(false);
    } else {
        new Master.FormKategoriMainan().setVisible(true); 
    }
    }//GEN-LAST:event_btnBukaFormDataKategoriActionPerformed

    private void btnBukaFormDataMainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaFormDataMainanActionPerformed
    FormDataMainan frmMainan = new FormDataMainan(this.frameMenuUtama); 
    frmMainan.setVisible(true);
    if (this.frameMenuUtama != null) {
        this.frameMenuUtama.setVisible(false); 
    } 
    }//GEN-LAST:event_btnBukaFormDataMainanActionPerformed

    private void btnBukaFormDataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaFormDataSupplierActionPerformed
    if (this.frameMenuUtama != null) {
        Master.FormDataSupplier frmSupplier = new Master.FormDataSupplier(this.frameMenuUtama); 
        frmSupplier.setVisible(true);
        this.frameMenuUtama.setVisible(false);
    } else {
        new Master.FormDataSupplier().setVisible(true); 
    }
    }//GEN-LAST:event_btnBukaFormDataSupplierActionPerformed

    private void btnBukaFormDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaFormDataPelangganActionPerformed
    if (this.frameMenuUtama != null) {
        Master.FormPelanggan frmPelanggan = new Master.FormPelanggan(this.frameMenuUtama);
        frmPelanggan.setVisible(true);
        this.frameMenuUtama.setVisible(false);
    } else {
        new Master.FormPelanggan().setVisible(true);
    }
    }//GEN-LAST:event_btnBukaFormDataPelangganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBukaFormDataKategori;
    private javax.swing.JButton btnBukaFormDataMainan;
    private javax.swing.JButton btnBukaFormDataPelanggan;
    private javax.swing.JButton btnBukaFormDataSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelKontenUtama;
    // End of variables declaration//GEN-END:variables
}
