package MenuUtama;
import Laporan.FormLaporanDataPelanggan;
import Laporan.FormLaporanPembelian;
import Laporan.FormLaporanPenjualan;
import Laporan.FormLaporanStok;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import koneksi.koneksi;

public class PanelLaporanPilihan extends javax.swing.JPanel {
    private MenuUtama frameMenuUtama;
   
     public PanelLaporanPilihan(MenuUtama frameUtamaDariPemanggil) {
        initComponents();
        this.frameMenuUtama = frameUtamaDariPemanggil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKontenUtama = new javax.swing.JPanel();
        btnLapPenjualan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLapPembelian = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLapStokMainan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnLapPelanggan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        panelKontenUtama.setBackground(new java.awt.Color(0, 77, 100));
        panelKontenUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLapPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LaporanPenjualan.png"))); // NOI18N
        btnLapPenjualan.setBorderPainted(false);
        btnLapPenjualan.setContentAreaFilled(false);
        btnLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPenjualanActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnLapPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENJUALAN");
        panelKontenUtama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 220, 40));

        btnLapPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LaporanPembelian.png"))); // NOI18N
        btnLapPembelian.setBorderPainted(false);
        btnLapPembelian.setContentAreaFilled(false);
        btnLapPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPembelianActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnLapPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 200, 200));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEMBELIAN");
        panelKontenUtama.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 230, 230, -1));

        btnLapStokMainan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LaporanStok.png"))); // NOI18N
        btnLapStokMainan.setBorderPainted(false);
        btnLapStokMainan.setContentAreaFilled(false);
        btnLapStokMainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapStokMainanActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnLapStokMainan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 200, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Stok");
        panelKontenUtama.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 190, -1));

        btnLapPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LaporanPelanggan.png"))); // NOI18N
        btnLapPelanggan.setBorderPainted(false);
        btnLapPelanggan.setContentAreaFilled(false);
        btnLapPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPelangganActionPerformed(evt);
            }
        });
        panelKontenUtama.add(btnLapPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, 200));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PELANGGAN");
        panelKontenUtama.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 510, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelKontenUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelKontenUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPenjualanActionPerformed
    if (this.frameMenuUtama != null) {
        FormLaporanPenjualan frmInputJual = new FormLaporanPenjualan(this.frameMenuUtama);
        frmInputJual.setVisible(true);
        this.frameMenuUtama.setVisible(false);
      }
    }//GEN-LAST:event_btnLapPenjualanActionPerformed

    private void btnLapPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPembelianActionPerformed
        if (this.frameMenuUtama != null) {
        FormLaporanPembelian frmInputBeli = new FormLaporanPembelian(this.frameMenuUtama); // Panggil konstruktor baru
        frmInputBeli.setVisible(true);
        this.frameMenuUtama.setVisible(false);
      }
    }//GEN-LAST:event_btnLapPembelianActionPerformed

    private void btnLapPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPelangganActionPerformed
        try {
            if (this.frameMenuUtama == null) {
                JOptionPane.showMessageDialog(this, "Error: Referensi ke Menu Utama tidak valid.", "Error Navigasi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Connection conn = new koneksi().connect();
            String pathJasper = "/Laporan/LaporanPelanggan.jasper"; 
            InputStream jasperStream = getClass().getResourceAsStream(pathJasper);
            HashMap<String, Object> parameter = new HashMap<>(); 
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperStream, parameter, conn);
            if (jasperPrint.getPages().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada data pelanggan untuk ditampilkan.", "Informasi Laporan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.frameMenuUtama.setVisible(false); 
                JasperViewer viewer = new JasperViewer(jasperPrint, false);
                viewer.addWindowListener(new WindowAdapter() {
                    public void windowClosed(WindowEvent e) {
                        if (frameMenuUtama != null) {
                            frameMenuUtama.tampilkanPanel("Laporan"); 
                            frameMenuUtama.setVisible(true);
                        }
                    }
                });
                viewer.setTitle("Laporan Data Pelanggan");
                viewer.setVisible(true);
            }
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan Laporan Pelanggan: " + e.getMessage(), "Error Laporan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan umum saat membuat Laporan Pelanggan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLapPelangganActionPerformed

    private void btnLapStokMainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapStokMainanActionPerformed
        if (this.frameMenuUtama != null) {
        FormLaporanStok frmInputStok = new FormLaporanStok(this.frameMenuUtama); 
        frmInputStok.setVisible(true);
        this.frameMenuUtama.setVisible(false);
      }
    }//GEN-LAST:event_btnLapStokMainanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapPelanggan;
    private javax.swing.JButton btnLapPembelian;
    private javax.swing.JButton btnLapPenjualan;
    private javax.swing.JButton btnLapStokMainan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelKontenUtama;
    // End of variables declaration//GEN-END:variables
}
