package Master;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import MenuUtama.MenuUtama;

public class FormPelanggan extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private MenuUtama menuUtamaAsal;

    public FormPelanggan() {
        initComponents();
        setLocationRelativeTo(null);
        kosong();
        aktif();
        datatable();
        autonumberIdPelanggan();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public FormPelanggan(MenuUtama pemanggilMenu) {
    initComponents();
    this.menuUtamaAsal = pemanggilMenu;
    setLocationRelativeTo(pemanggilMenu);
     kosong();
     aktif();
     datatable();
     autonumberIdPelanggan();
     setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    protected void aktif(){
        txtNamaPelanggan.requestFocus();
        buttonGroup1.clearSelection();
    }
    
    protected void kosong(){
        autonumberIdPelanggan();
        txtNamaPelanggan.setText("");
        txtAlamat.setText("");
        txtNoTelepon.setText("");
        buttonGroup1.clearSelection();
    }
    
    protected void datatable(){
    Object[] Baris = {"ID Pelanggan", "Nama", "Jenis Kelamin", "Alamat", "No Telepon"};
    tabmode = new DefaultTableModel(null, Baris);
    tablePelanggan.setModel(tabmode);
    String cariItem = txtCari.getText();
    try {
        String sql = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ? ORDER BY id_pelanggan ASC";      
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, "%" + cariItem + "%");
        stat.setString(2, "%" + cariItem + "%");       
        ResultSet hasil = stat.executeQuery();
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString("id_pelanggan"),
                hasil.getString("nama_pelanggan"),
                hasil.getString("jenis_kelamin"),
                hasil.getString("alamat"),
                hasil.getString("no_telp")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal ditampilkan: " + e);
        e.printStackTrace();
    }
}

    protected void autonumberIdPelanggan() {
    try {
        String sql = "SELECT id_pelanggan FROM pelanggan ORDER BY id_pelanggan DESC LIMIT 1";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);     
        txtIdPelanggan.setText("P001");      
        if (rs.next()) {
            String id_pelanggan_terakhir = rs.getString("id_pelanggan").substring(1); 
            int AN = Integer.parseInt(id_pelanggan_terakhir) + 1;
            String Nol = "";
            if (AN < 10) { Nol = "00"; }
            else if (AN < 100) { Nol = "0"; }
            txtIdPelanggan.setText("P" + Nol + AN);
        }
    } catch (Exception e) { 
        JOptionPane.showMessageDialog(null, "Auto Number ID Pelanggan Gagal: " + e);
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtIdPelanggan = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        rlaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        txtAlamat = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        tabelPelanggan = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHomeDariMainan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSimpan1 = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        btnKeluar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdPelanggan.setEditable(false);
        jPanel1.add(txtIdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 210, 30));
        jPanel1.add(txtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 210, 30));

        buttonGroup1.add(rlaki);
        rlaki.setText("Laki-Laki");
        jPanel1.add(rlaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, 30));

        buttonGroup1.add(rperempuan);
        rperempuan.setText("Perempuan");
        jPanel1.add(rperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 30));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 210, 30));
        jPanel1.add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 210, 30));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 170, 30));

        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePelanggan.setGridColor(new java.awt.Color(0, 0, 0));
        tablePelanggan.setShowGrid(true);
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        tabelPelanggan.setViewportView(tablePelanggan);

        jPanel1.add(tabelPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 1170, 110));

        jPanel2.setBackground(new java.awt.Color(33, 111, 134));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("DATA PELANGGAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 90));

        btnHomeDariMainan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHomeDariMainan.setForeground(new java.awt.Color(255, 255, 255));
        btnHomeDariMainan.setText("HOME");
        btnHomeDariMainan.setContentAreaFilled(false);
        btnHomeDariMainan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeDariMainanActionPerformed(evt);
            }
        });
        jPanel2.add(btnHomeDariMainan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home-button.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 40, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 111, 134));
        jLabel8.setText("ID PELANGGAN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 111, 134));
        jLabel9.setText("NAMA PELANGGAN");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 111, 134));
        jLabel11.setText("JENIS KELAMIN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(33, 111, 134));
        jLabel12.setText("ALAMAT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(33, 111, 134));
        jLabel13.setText("NO. TELEPON");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, 30));

        btnSimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Desain tanpa judul.png"))); // NOI18N
        btnSimpan1.setBorderPainted(false);
        btnSimpan1.setContentAreaFilled(false);
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 110, 60));

        btnEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ButtonEdit.png"))); // NOI18N
        btnEdit1.setBorderPainted(false);
        btnEdit1.setContentAreaFilled(false);
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 120, 60));

        btnHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ButtonDelete.png"))); // NOI18N
        btnHapus1.setBorderPainted(false);
        btnHapus1.setContentAreaFilled(false);
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 120, 60));

        btnBatal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ButtonClear.png"))); // NOI18N
        btnBatal1.setBorderPainted(false);
        btnBatal1.setContentAreaFilled(false);
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 120, 60));

        btnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ButtonKeluar.png"))); // NOI18N
        btnKeluar1.setBorderPainted(false);
        btnKeluar1.setContentAreaFilled(false);
        btnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 120, 60));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("CARI");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        int bar = tablePelanggan.getSelectedRow();
        String id = tabmode.getValueAt(bar, 0).toString();
        String nama = tabmode.getValueAt(bar, 1).toString();
        String jk = tabmode.getValueAt(bar, 2).toString();
        String alamat = tabmode.getValueAt(bar, 3).toString();
        String telepon = tabmode.getValueAt(bar, 4).toString();
        txtIdPelanggan.setText(id);
        txtNamaPelanggan.setText(nama);
        if (jk.equals("Laki-laki")) {
            rlaki.setSelected(true);
        } else {
            rperempuan.setSelected(true);
        }
        txtAlamat.setText(alamat);
        txtNoTelepon.setText(telepon);
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        datatable();
    }//GEN-LAST:event_txtCariKeyReleased

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
         int bar = tablePelanggan.getSelectedRow();
        String id = tabmode.getValueAt(bar, 0).toString();
        String nama = tabmode.getValueAt(bar, 1).toString();
        String jk = tabmode.getValueAt(bar, 2).toString();
        String alamat = tabmode.getValueAt(bar, 3).toString();
        String telepon = tabmode.getValueAt(bar, 4).toString();
        txtIdPelanggan.setText(id);
        txtNamaPelanggan.setText(nama);
        if (jk.equals("Laki-laki")) {
            rlaki.setSelected(true);
        } else {
            rperempuan.setSelected(true);
        }
        txtAlamat.setText(alamat);
        txtNoTelepon.setText(telepon);
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void btnHomeDariMainanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeDariMainanActionPerformed
        this.dispose();
        MenuUtama menu = new MenuUtama();
        menu.setVisible(true);
    }//GEN-LAST:event_btnHomeDariMainanActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        String jk = rlaki.isSelected() ? "Laki-laki" : rperempuan.isSelected() ? "Perempuan" : "";
        try {
            String sql = "INSERT INTO pelanggan (id_pelanggan, nama_pelanggan, alamat, no_telp, jenis_kelamin) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtIdPelanggan.getText());
            stat.setString(2, txtNamaPelanggan.getText());
            stat.setString(3, txtAlamat.getText());
            stat.setString(4, txtNoTelepon.getText());
            stat.setString(5, jk);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            kosong();
            txtIdPelanggan.requestFocus();
            datatable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e);
        }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        String jk = rlaki.isSelected() ? "Laki-laki" : rperempuan.isSelected() ? "Perempuan" : "";
        try {
            String sql = "UPDATE pelanggan SET nama_pelanggan=?, jenis_kelamin=?, alamat=?, no_telp=? WHERE id_pelanggan=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtNamaPelanggan.getText());
            stat.setString(2, jk);
            stat.setString(3, txtAlamat.getText());
            stat.setString(4, txtNoTelepon.getText());
            stat.setString(5, txtIdPelanggan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            datatable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah: " + e);
        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                String sql = "DELETE FROM pelanggan WHERE id_pelanggan=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtIdPelanggan.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                kosong();
                datatable();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus: " + e);
            }
        }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        kosong();
        aktif();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluar1ActionPerformed
        this.dispose();
    if (menuUtamaAsal != null) {
        menuUtamaAsal.tampilkanPanel("Master"); 
        menuUtamaAsal.setVisible(true); 
    } else {
        new MenuUtama().setVisible(true);
    }
    }//GEN-LAST:event_btnKeluar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnHomeDariMainan;
    private javax.swing.JButton btnKeluar1;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rlaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JScrollPane tabelPelanggan;
    private javax.swing.JTable tablePelanggan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoTelepon;
    // End of variables declaration//GEN-END:variables
}
